version: '3'

services:

  node-app:
    restart: always
    build: .
    ports:
      - "3000:3000" # {local port}:{container port}
    volumes:
      - /root/app/node_modules
      - ./app:/root/app
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: devdev.21FirstTkc@
      DB_PORT: 3306

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: devdev.21FirstTkc@
      MYSQL_DATABASE: dev_first_vue
      MYSQL_PASSWORD: devdev.21FirstTkc@
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
