version: '3'

services:

  node-app:
    restart: always
    build: .
    ports:
      - "3000:3000" # {local port}:{container port}
    volumes:
      - /root/app/node_modules
      - ./app:/root/app
    links:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: dev_first_vue
      MYSQL_ROOT_PASSWORD: devdev.21FirstTkc@
      # もしかしたらrootのみいればいいのかも
      # MYSQL_USER: devuser
      # MYSQL_PASSWORD: devdev.21FirstTkc@
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    # volumes:
    #   # 実データ
    #   - ./data/mysql:/var/lib/mysql
    #   # mysqlの設定ファイル
    #   - ./data/my.cnf:/etc/mysql/conf.d/my.cnf
